spring.application.name=nosql
#
spring.data.mongodb.uri=mongodb://localhost:27017/database
spring.data.mongodb.database=database
#
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository.query=DEBUG
